name: CI

on:
  push:
    branches:
      - user-service  
  pull_request:
    branches:
      - user-service

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_ACCESS_TOKEN_SECRET: 09f26e402586e2faa8da4c98a35f1b20d6b033c6097befa8be3486a829587fe2f90a832bd3ff9d42710a4da095a2ce285b009f0c3730cd9b8e1af3eb84df6611
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test