name: CI

on:
  push:
    branches:
      - order-service 
  pull_request:
    branches:
      - order-service

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test